<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VipModule</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemModule\SystemModule.csproj" />
    <ProjectReference Include="..\..\OpenMir2\OpenMir2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.3.1" />
    <PackageReference Include="NLog" Version="5.2.7" />
  </ItemGroup>

</Project>
